---
name: main

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 8
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm install
      - name: Publish
        run: bundle exec rake build
